### PR TITLE
Update Java submodule for Bionic Beaver support

### PR DESCRIPTION
**Pull request by BronsonQuick**
When we're provisioning this extension on Bionic Beaver the following error occurs due to the newest version of Puppet. Bumping the Java submodule fixes this error.

>default: Error: Evaluation Error: Error while evaluating a Function Call, unsupported release bionic (file: /vagrant/extensions/chassis_elasticsearch/modules/java/manifests/params.pp, line: 143, column: 20) on node vagrant.local
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

### CODE REVIEW

**Comment by BronsonQuick** [comment]
Blocked until: https://github.com/Chassis/Chassis/pull/532 is merged.

**Comment by roborourke** [comment]
What was the error this fixes?

**Comment by BronsonQuick** [comment]
When I opened this WIP originally I thought that there would be more to it and I was gonna circle back. Turns out this was the only fix I needed. I'll do another provision with the extension in it's existing state with the Bionic Beaver branch and update the PR.

**Comment by BronsonQuick** [comment]
@roborourke I've updated the issue with the provisioning error.

**Comment by roborourke** [comment]
Does this work with Xenial too? If not try using tag 2.3.0 or 2.4.0

**Comment by BronsonQuick** [comment]
On Xenial with this submodule update I get the following error:
>==> default: Error: Syntax error at 'String'; expected ')' at /vagrant/extensions/chassis_elasticsearch/modules/java/manifests/init.pp:39

I'll try those tags now on both branches.

**Comment by BronsonQuick** [comment]
@roborourke 2.3.0 and 2.4.0 have the same error so it looks like we can't have it working for both Xenial and Bionic as they didn't make the Puppet stuff backwards compatible.

**Comment by roborourke** [comment]
Crap, I was afraid of that. There’s def no way to get chassis v2 to grab a particular tag from here if available? Do you think it’d be a lot of effort to make core look for a tag that matches the chassis version before falling back to master?

**Comment by BronsonQuick** [comment]
@roborourke I'll have a think about that overnight and see if I can come up with something to handle that. Seeing we've got the ability to add custom variables in extensions in Chassis core as of yesterday I reckon I might be able to add the tag as a variable and work around it that way

**Pull request merged**
